---

asset:
- changed-files:
  - any-glob-to-any-file: 'assets/**/*'

documentation:
- changed-files:
  - any-glob-to-any-file: 'README.md'

build:
- changed-files:
  - any-glob-to-any-file: ['build.zig.zon', 'build.zig']

config:
- changed-files:
  - any-glob-to-any-file: 'src/config.zig'

cli:
- changed-files:
  - any-glob-to-any-file: 'src/cli.zig'

daemon:
- changed-files:
  - any-glob-to-any-file: 'src/daemon/**/*'

util:
- changed-files:
  - any-glob-to-any-file: 'src/util.zig'

core:
- changed-files:
  - any-glob-to-any-file: ['src/core.zig', 'src/dotfile.zig']

engine:
- changed-files:
  - any-glob-to-any-file: 'src/lib.zig'

test:
- changed-files:
  - any-glob-to-any-file: 'test/**/*'

ops:
- changed-files:
  - any-glob-to-any-file: ['.github/**/*', 'codecov.yml']

feature:
 - head-branch: ['^feature', 'feature']
