---
name: CD
"on":
  workflow_call:
    inputs:
      tag_name:
        required: true
        type: string

permissions:
  id-token: write
  contents: read
  attestations: read
  pages: write

env:
  ZIG_VERSION: 0.16.0

jobs:
  release:
    name: Create release
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Publish release
        uses: taiki-e/create-gh-release-action@v1
        with:
          changelog: CHANGELOG.md
          token: ${{ secrets.GITHUB_TOKEN }}

  build-linux-arm:
    name: Build / Linux ARM
    runs-on: ubuntu-24.04-arm
    needs: [release]
    permissions:
      id-token: write
      contents: write
      attestations: write

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libdbus-1-dev pkg-config

      - name: Install Zig
        uses: mlugg/setup-zig@v2
        with:
          version: ${{ env.ZIG_VERSION }}

      - name: Build
        run: |
          zig build --release=safe
          mv zig-out/bin/dfs dfs
          tar -czvf dfs-linux-aarch64.tar.gz dfs

      - name: Upload
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        run: |
          gh release upload ${{ inputs.tag_name }} \
          dfs-linux-aarch64.tar.gz

      - name: Attest
        uses: actions/attest-build-provenance@v4
        with:
          subject-path: "dfs-linux-aarch64.tar.gz"

      - name: Verify attestation
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        run: |
          gh attestation verify dfs-linux-aarch64.tar.gz --owner "$GITHUB_REPOSITORY_OWNER"

  build-linux-x86:
    name: Build / Linux X86
    runs-on: ubuntu-latest
    needs: [release]
    permissions:
      id-token: write
      contents: write
      attestations: write

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libdbus-1-dev pkg-config

      - name: Install Zig
        uses: mlugg/setup-zig@v2
        with:
          version: ${{ env.ZIG_VERSION }}

      - name: Build
        run: |
          zig build --release=safe
          mv zig-out/bin/dfs dfs
          tar -czvf dfs-linux-x86_64.tar.gz dfs

      - name: Upload
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        run: |
          gh release upload ${{ inputs.tag_name }} \
          dfs-linux-x86_64.tar.gz

      - name: Attest
        uses: actions/attest-build-provenance@v4
        with:
          subject-path: "dfs-linux-x86_64.tar.gz"

      - name: Verify attestation
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        run: |
          gh attestation verify dfs-linux-x86_64.tar.gz --owner "$GITHUB_REPOSITORY_OWNER"

  build-macos:
    name: Build / macOS
    runs-on: macos-latest
    needs: [release]
    permissions:
      id-token: write
      contents: write
      attestations: write

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Install dependencies
        run: |
          brew update
          brew install dbus

      - name: Install Zig
        uses: mlugg/setup-zig@v2
        with:
          version: ${{ env.ZIG_VERSION }}

      - name: Build
        run: |
          zig build --release=safe
          mv zig-out/bin/dfs dfs
          tar -czvf dfs-macos.tar.gz dfs

      - name: Upload
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        run: |
          gh release upload ${{ inputs.tag_name }} \
          dfs-macos.tar.gz

      - name: Attest
        uses: actions/attest-build-provenance@v4
        with:
          subject-path: "dfs-macos.tar.gz"

      - name: Verify attestation
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        run: |
          gh attestation verify dfs-macos.tar.gz \
          --owner "$GITHUB_REPOSITORY_OWNER"

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libdbus-1-dev pkg-config

      - name: Setup Pages
        uses: actions/configure-pages@45bfe0192ca1faeb007ade9deae92b16b8254a0d

      - uses: mlugg/setup-zig@v2
        with:
          version: ${{ env.ZIG_VERSION }}

      - name: Build docs
        run: zig build docs

      - name: Upload artifact
        uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9
        with:
          path: "docs"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@cd2ce8fcbc39b97be8ca5fce6e763baed58fa128
